### ISSUE TITLE
Error promise not launched on scan fail

### ISSUE THREAD

**Issue by anasbihi** [rdn87/cordova-plugin-gctouch-id#1]
Hi,
I'm having a issue when I try to use a finger print that is not registred on device.
I was expecting having an error that should be coming from cordova plugin onFail execution but nothing happened.

Can you help ?

Down below is the code i've used to handle fingerprints authentication

`
**
GCTouchID.authWithTouchID(
                function (msg) {
                    dfd.resolve();},
                function(msg) {
                    debugger;
                    dfd.reject(msg);},
                {
                    insertPwd: "false",
                    textValue: "Insert PWD",
                    message: $translate.instant('MESSAGE'),
                    security: "true"
                });**
`

**Comment by anasbihi** [comment]
I've found a fix for my issue. PR sent in order to fix that

**Comment by rdn87** [comment]
Thank you so much, when I Create this plugin with Xcode 7 i don't have this problems.
